### ISSUE TITLE
As a user, be able to get reminders of Birthday of all contacts, so that I never miss out on important dates

### ISSUE THREAD

**Issue by tshradheya** [CS2103AUG2017-W14-B1/main#27] opened 2017-09-25 09:42 UTC

**Comment by chuaweiwen** [comment] 2017-09-30 12:46
Duplicate of #12

**Comment by justinpoh** [comment] 2017-10-04 09:42
As a user who often help celebrate friends' birthdays

**Closed as completed** 2017-10-09 13:51 UTC
Labels: type.story, priority.high, status.done
